### ISSUE TITLE
Entrevista.

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/entrevista-equipo-exe#1]
La entrevista se encuentra alojada en Youtube, en formato de video. Ahí todos los detalles.
https://www.youtube.com/watch?v=Xhgs8vWb-ng

Equipo .exe
-Fernando Miguel López
-Luis Carlos Rendón Aparicio
-Nayeli Anai González López
-Arturo Angón José

**Comment by Rmz-Rigo** [comment]
CALIFICACIÓN: 20/20.

Calificado por:
-Lizzete León González
-Gandhi Salazar Cruz
-Francisco Isaías Ballesteros Huerta
-Rigoberto Ramírez Nicolás

**Comment by josealfredo79** [comment]
Falto el reporte de la practica.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
